# configuration
language: java
cache:
    - apt
    - $HOME/.m2

# build matrix
jdk:
    - oraclejdk7
    - openjdk7
env:
    - UNIT_TESTS=true
    - PIPELINE_TESTS=true
    - PIPELINE_TESTS=true RUN_LOCAL="-runLocal"

# run steps
install:
    - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
    - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys  # no pw required for ssh'ing locally
    - ssh localhost -o StrictHostKeyChecking=false -n  # allow us to ssh later w/out typing "yes"
    - sudo apt-get install graphviz
    - mvn install -am -pl genomix/genomix-driver/ -DskipTests=true # only install driver's prereq's

before_script:
    - cd genomix/genomix-pregelix/
    - java -classpath target/genomix-pregelix-0.2.10-SNAPSHOT-jar-with-dependencies.jar:target/test-classes/ edu.uci.ics.genomix.pregelix.jobgen.JobGenerator
    - cd ../..
script:
    - cd genomix
    - ./run_tests.sh
